---
- name: This playbook will install nginx
  hosts: server
  become: true

  tasks:
    - name: Install the nginx
      apt:
        name: nginx
        state: present

    - name: Start the nginx service
      service:
        name: nginx
        state: started
        enabled: true